# Generated by Django 2.2.4 on 2019-08-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),
        migrations.AddField(
            model_name='job',
            name='_summary',
            field=models.CharField(default='', max_length=200, verbose_name='Summary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
