# Generated by Django 2.2.4 on 2019-08-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190818_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='_summary',
        ),
        migrations.AddField(
            model_name='job',
            name='details',
            field=models.TextField(default='Details', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Details', max_length=50),
            preserve_default=False,
        ),
    ]
