# Generated by Django 2.2.4 on 2019-08-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190817_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='_pub_date',
            new_name='Publication Date',
        ),
    ]
