# Generated by Django 2.2.4 on 2019-08-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190817_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Publication Date',
            new_name='_pub_date',
        ),
    ]
